### PR TITLE
R43

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by owlseye** [comment]
I told you before....DONT DO THIS!

**Comment by akhilnarang** [comment]
lmao

**Comment by ghost** [comment]
wtf its to old r22

**Comment by owlseye** [comment]
Learn about Anroid before talking shit and pull requesting the same shit.

**Comment by ghost** [comment]
wow you are an pro?

**Comment by owlseye** [comment]
Well, that's your interpretation. 
So, let me explain:
`<default revision="refs/tags/android-6.0.1_r22"
           remote="aosp"
           sync-j="4"
           sync-c="true"
           sync-f="true" />`

Revision is the branch which will be tracked from the AOSP git. But as you can see we don't only have repos from AOSP, we also have own ones, with additional commits, features, etc. Since we forked them we need to update them from time to time, but as Orion is based on AOSPB (and our repos are mostly forks of their repos) we need to wait until they update their repositories so we can update ours as well. No reason to track newer branches while other repos aren't at the same stage.

**Comment by ghost** [comment]
i am building it for my device

**Comment by owlseye** [comment]
Aha. What is the relation to what I just said?

**Comment by ghost** [comment]
okay man sry

**Pull request closed without merging**
